# Development overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f compose.dev.yaml up

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    volumes:
      - .:/var/www
      - /var/www/vendor
      - /var/www/var/cache
      - /var/www/var/log
    command: >
      sh -c "
        composer install &&
        php-fpm
      "

  nginx:
    volumes:
      - .:/var/www
      - /var/www/vendor
